version: 2.1


orbs:
  win: circleci/windows@2.2.0


workflows:
  build:
    jobs:
      - build-windows-pyinstaller-commercial


jobs:
  build-windows-pyinstaller-commercial:
    executor:
      name: win/default
      shell: bash.exe
    steps:
      - checkout
      - win-install-sys-deps:
          ffmpeg-version: ""
          gstreamer-version: ""
          qt-version: "5.15.2"
#      - win-install-python-deps:
#          poetry-version: "1.1.4"

commands:

  win-install-ffmpeg:
    parameters:
      ffmpeg-version:
        type: string
    steps:
      - run: echo 1

  win-install-gstreamer:
    parameters:
      gstreamer-version:
        type: string
    steps:
      - restore_cache:
          keys:
            - gstreamer-v0-<< parameters.gstreamer-version >>
      - run: |
          wget -O ~/Downloads/gstreamer.msi https://gstreamer.freedesktop.org/data/pkg/windows/1.18.3/msvc/gstreamer-1.0-msvc-x86_64-1.18.3.msi
          ~/Downloads/gstreamer.msi /?
      - save_cache:
          paths:
            - ~/Downloads/gstreamer.msi
          key: gstreamer-v0-<< parameters.gstreamer-version >>

  win-install-qt:
    parameters:
      qt-version:
        type: string
      install-dir:
        type: string
        default: "C:/Program Files/Qt/"
      arch:
        type: string
        default: win64_msvc2019_64
    steps:
      - restore_cache:
          keys:
            - qt-v0-<< parameters.qt-version >>-<< parameters.arch >>
      - run: |
          pip install aqtinstall
          aqt install --outputdir "<< parameters.install-dir >>" << parameters.qt-version >> windows desktop << parameters.arch >>
      - save_cache:
          paths:
            - << parameters.install-dir >>
          key: qt-v0-<< parameters.qt-version >>-<< parameters.arch >>


  win-install-sys-deps:
    parameters:
      gstreamer-version:
        type: string
      ffmpeg-version:
        type: string
      qt-version:
        type: string
    steps:
      - win-install-qt:
          qt-version: << parameters.qt-version >>
      - win-install-gstreamer:
          gstreamer-version: << parameters.gstreamer-version >>
      - win-install-ffmpeg:
          ffmpeg-version: << parameters.ffmpeg-version >>
