version: 2.1


orbs:
  win: circleci/windows@2.2.0


workflows:
  build:
    jobs:
      - build-windows-pyinstaller-commercial


jobs:
  build-windows-pyinstaller-commercial:
    executor:
      name: win/default
      shell: bash.exe -e
    steps:
      - win-install-sys-deps:
          ffmpeg-version: ""
          gstreamer-version: "1.18.3"
          qt-version: "5.15.2"
          poetry-version: "1.1.4"
      - checkout
#      - win-install-python-deps:


commands:

  bash-add-to-path:
    parameters:
      path:
        type: string
    steps:
      - run:
          name: "Add to Bash PATH"
          command: |
            # Replace C: with /c
            NEW_PATH="<< parameters.path >>"
            NEW_BASH_PATH=${NEW_PATH/C:/\/c}
            QUOTED_PATH_VAR="\"PATH=${NEW_BASH_PATH}:${PATH}\""
            echo "export ${QUOTED_PATH_VAR}" >> ${BASH_ENV}

  win-add-to-path:
    parameters:
      path:
        type: string
    steps:
      - run:
          name: "Add to Windows global Path"
          command: |
            # Accept paths with forward slashes
            $fmtPath = "<< parameters.path >>".Replace('/', '\')
            $newPath = "$fmtPath;$env:Path"

            [Environment]::SetEnvironmentVariable("Path", $newPath, [EnvironmentVariableTarget]::Machine)

            # Print saved value to be sure
            [Environment]::GetEnvironmentVariable("Path", [EnvironmentVariableTarget]::Machine)
          shell: powershell.exe
      - bash-add-to-path:
          # Add to bash PATH which doesn't seem to source from Windows global Path
          path: << parameters.path >>

  win-install-ffmpeg:
    parameters:
      ffmpeg-version:
        type: string
    steps:
      - run: echo 1

  win-install-gstreamer:
    parameters:
      gstreamer-version:
        type: string
      install-dir:
        type: string
        # GStreamer refuses to install to 64bit Program Files
        default: "C:/Program Files (x86)/GStreamer/"
    steps:
      - restore_cache:
          keys:
            - gstreamer-v1-<< parameters.gstreamer-version >>
      - run:
          # Use Powershell to download so we don't have to worry about getting curl or wget installed
          name: "Download GStreamer installer"
          command: |
            $downloadUrl = "https://gstreamer.freedesktop.org/data/pkg/windows/<< parameters.gstreamer-version >>/msvc/gstreamer-1.0-msvc-x86_64-<< parameters.gstreamer-version >>.msi"
            $downloadFile = "$HOME/Downloads/gstreamer.msi"

            If (Test-Path $downloadFile) {
                Write-Host "GStreamer installer restored from cache to $downloadFile"
                Exit
            }

            (new-object System.Net.WebClient).DownloadFile("$downloadUrl", "$downloadFile")
          shell: powershell.exe
          environment:
            DOWNLOAD_URL:
      - run:
          # Why there are backticks: https://stackoverflow.com/a/44499001
          # Also msiexec only works with backslash paths
          name: "Install GStreamer"
          command: |
            If (Test-Path "<< parameters.install-dir >>/*") {
                Write-Host "GStreamer restored from cache to << parameters.install-dir >>"
                Exit
            }

            $msiFile = "$HOME/Downloads/gstreamer.msi".Replace('/', '\')
            $installDir = "`"<< parameters.install-dir >>`"".Replace('/', '\')

            # https://gstreamer.freedesktop.org/documentation/installing/on-windows.html?gi-language=c
            # https://gstreamer.freedesktop.org/documentation/deploying/windows.html
            # https://stackoverflow.com/q/63838725/8134178
            Start-Process msiexec -ArgumentList "/i $msiFile INSTALLDIR=$installDir ALLUSERS=1 Complete=1 /qn" -Wait -Passthru

            If (Test-Path "<< parameters.install-dir >>/*") { Write-Host "GStreamer succesfully installed to << parameters.install-dir >>" }
            Else { Throw "GStreamer was not properly installed to << parameters.install-dir >>" }
          shell: powershell.exe
      - win-add-to-path:
          path: << parameters.install-dir >>/1.0/msvc_x86_64/bin/
      - run:
          name: "Ensure GStreamer properly installed"
          command: gst-inspect-1.0 --gst-version
      - save_cache:
          paths:
            - ~/Downloads/gstreamer.msi
            - << parameters.install-dir >>
          key: gstreamer-v1-<< parameters.gstreamer-version >>

  win-install-poetry:
    parameters:
      poetry-version:
        type: string
    steps:
      - run:
          name: "Install Poetry"
          command: |
            $poetryVersion = "<< parameters.poetry-version >>
            $downloadUrl = "https://raw.githubusercontent.com/python-poetry/poetry/$poetryVersion/get-poetry.py"
            (Invoke-WebRequest -Uri $downloadUrl -UseBasicParsing).Content | python - --version $poetryVersion
      - run:
          name: "Ensure Poetry installed and in Path"
          command: poetry --version

  win-install-qt:
    parameters:
      qt-version:
        type: string
      install-dir:
        type: string
        default: "C:/Program Files/Qt/"
      arch:
        type: string
        default: win64_msvc2019_64
    steps:
      - restore_cache:
          keys:
            - qt-v0-<< parameters.qt-version >>-<< parameters.arch >>
      - run:
          name: "Install Qt"
          command: |
            if [ -d "<< parameters.install-dir >>" ]; then
                echo "Qt already installed. Skipping"
                exit 0; fi
            pip install aqtinstall
            aqt install --outputdir "<< parameters.install-dir >>" << parameters.qt-version >> windows desktop << parameters.arch >>
      - save_cache:
          paths:
            - << parameters.install-dir >>
          key: qt-v0-<< parameters.qt-version >>-<< parameters.arch >>

  win-install-sys-deps:
    parameters:
      gstreamer-version:
        type: string
      ffmpeg-version:
        type: string
      poetry-version:
        type: string
      qt-version:
        type: string
    steps:
      - win-install-qt:
          qt-version: << parameters.qt-version >>
      - win-install-gstreamer:
          gstreamer-version: << parameters.gstreamer-version >>
      - win-install-ffmpeg:
          ffmpeg-version: << parameters.ffmpeg-version >>
      - win-install-poetry:
          poetry-version: << parameters.poetry-version >>
