name: PyInstaller Linux

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:

      - name: "Checkout repository"
        uses: actions/checkout@v2

      - name: "Set up SSH access"
        uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.GSTLY_DEPLOY_KEY }}

      - name: "Install Qt"
        uses: jurplel/install-qt-action@v2
        with:
          version: '5.15.2'
          host: linux
          target: desktop

      - name: "Install PyCairo/PyGObject dependencies"
        run: sudo apt install libgirepository1.0-dev libcairo2-dev gir1.2-gtk-3.0

      - name: "Set up python"
        uses: actions/setup-python@v2
        with:
          python-version: '3.6'

      - name: "Install poetry"
        uses: snok/install-poetry@v1.1.1
        with:
          version: 1.1.4

      - name: "Install dependencies"
        run: poetry install --no-dev -E client_build -E client_res_build

      - name: "Build resources"
        run: poetry run python scripts/compile_qt_resources.py
        working-directory: brainframe_qt/ui/

      - name: "Build PyInstaller image"
        run: poetry run pyinstaller deploy/pyinstaller/pyinstaller.spec
